version: "3"
services:

  wp:
    image: wordpress:5.5.3-php7.4-apache
    ports:
      - 8111:80
      - 8112:81
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wp-app
      - WORDPRESS_TABLE_PREFIX=wp
    volumes:
      - ./wp-app:/var/www/html
      - ./wp-sub:/var/www/sub
      - ./wp-config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./wp-config/ports.conf:/etc/apache2/ports.conf
      - ./wp-config/.htaccess:/var/www/sub/.htaccess

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp-app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  myadmin:
    image: phpmyadmin:latest
    ports:
      - 8787:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  db:
